### ISSUE TITLE
Topics not listed

### ISSUE THREAD

**Issue by plieningerweb** [EESC-LabRoM/rosweb#6]
JS Error
```
Uncaught ReferenceError: resposne is not defined
    at eval (eval at evaluate (:117:21), <anonymous>:1:1)
    at HTMLSelectElement.UpdateRosTopicSelectors.$.each (http://localhost:8000/js/bundle.js:1139:13)
    at Function.each (http://localhost:8000/js/jquery.min.js:2:2861)
    at n.fn.init.each (http://localhost:8000/js/jquery.min.js:2:845)
    at Frontend.UpdateRosTopicSelectors (http://localhost:8000/js/bundle.js:1132:34)
    at Ros.getTopics (http://localhost:8000/js/bundle.js:424:27)
    at http://localhost:8000/js/roslib.min.js:1:10425
    at d.<anonymous> (http://localhost:8000/js/roslib.min.js:1:13694)
    at d.listener (http://localhost:8000/js/eventemitter2.js:264:10)
    at d.EventEmitter.emit (http://localhost:8000/js/eventemitter2.js:328:19)
(anonymous) @ VM279:1
UpdateRosTopicSelectors.$.each @ frontend.ts:203
each @ jquery.min.js:2
each @ jquery.min.js:2
UpdateRosTopicSelectors @ frontend.ts:195
Ros.getTopics @ widget_instance.ts:160
(anonymous) @ roslib.min.js:1
(anonymous) @ roslib.min.js:1
listener @ eventemitter2.js:264
EventEmitter.emit @ eventemitter2.js:328
b @ roslib.min.js:1
c @ roslib.min.js:1
onmessage @ roslib.min.js:1


variable response is
["/rosout", "/rosout_agg"]

response has no response.topic attribute
```

**Comment by plieningerweb** [comment]
In the online version (http://labrom.eesc.usp.br/rosweb/) it is working.
It seems like getTopics() does not return the types, only the topics.

What do I have to do to get the current master version working?

**Comment by plieningerweb** [comment]
Reason seems to be failing submodule update
```
rosweb$ git submodule update
fatal: reference is not a tree: 242492b10bb2fd2c80d8b79b4aca53c471743d7c
Unable to checkout '242492b10bb2fd2c80d8b79b4aca53c471743d7c' in submodule path 'src/js/roslibjs'
```

**Comment by marcoarruda** [comment]
Fixed
Now the js libraries are static files, no more submodules to manage.
